import Products from "@/components/home/Products";
import React from "react";

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};

const ProductsPage = () => {
  return (
    <div className="w-11/12 mx-auto">
      <Products></Products>
    </div>
  );
};

export default ProductsPage;
